[package]
name = "qatrader_rs"
version = "0.1.0"
authors = ["yutiansut <yutiansut@qq.com>"]
edition = "2018"
description = "Quantitative Financial Framework"
repository = "https://github.com/yutiansut/qatrader_rs"
readme = "README.md"
documentation = "http://doc.yutiansut.com"
keywords = ["amqp", "rabbitmq", "quantaxis", "quant"]
categories = ["quant"]
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "0.3.11"
lapin = "^0.28"
log = "^0.4"
env_logger = "^0.7"